/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package data;

import com.sun.source.tree.IfTree;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.HeadlessException;
import java.util.Date;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;

/**
 *
 * @author Angga
 */
public class FSearch extends javax.swing.JFrame {
    /**
     * Creates new form FSearch
     */
    public FSearch() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void kosong_data(){
        kolommaster.setText("");
        kolommaster.requestFocus();
    }
    
    void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom Jumlah Hanya Bisa Memasukan Karakter Angka");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kolommaster = new javax.swing.JTextField();
        buttonmaster = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prakerja");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        kolommaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolommasterActionPerformed(evt);
            }
        });
        kolommaster.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmasterKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kolommasterKeyTyped(evt);
            }
        });

        buttonmaster.setText("CARI");
        buttonmaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasterActionPerformed(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SA (1).png"))); // NOI18N
        jLabel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));

        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Silahkan Masukan NIK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addContainerGap(277, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kolommaster, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonmaster)))
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonmaster)
                    .addComponent(kolommaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmasterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmasterKeyReleased
        // TODO add your handling code here:
        int posisi = kolommaster.getCaretPosition();
        kolommaster.setText(kolommaster.getText().toUpperCase());
        kolommaster.setCaretPosition(posisi);
    }//GEN-LAST:event_txtmasterKeyReleased

    private void btnmasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasterActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn=(java.sql.Connection)koneksi.configDB();
            String sql = "select * from masterdata where nik='"+kolommaster.getText()+"' or nama='"+kolommaster.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()){
                DialogUtama.nama.setText(rs.getString(2));
                DialogUtama.nik.setText(rs.getString(3));
                DialogUtama.no_kk.setText(rs.getString(4));
                DialogUtama.tgl.setDate(rs.getDate(6));
                DialogUtama.tempat.setText(rs.getString(5));
                DialogUtama.umur.setText(rs.getString(7));
                if ("PEREMPUAN".equals(rs.getString(8))) {
                    DialogUtama.rbperempuan.setSelected(true);
                } else{
                    DialogUtama.rblaki.setSelected(true);
                }
                DialogUtama.warga.setText(rs.getString(9));
                DialogUtama.provinsi.setText(rs.getString(10));
                DialogUtama.kecamatan.setText(rs.getString(11));
                DialogUtama.desa.setText(rs.getString(12));
                DialogUtama.dusun.setText(rs.getString(13));
                DialogUtama.kampung.setText(rs.getString(14));
                DialogUtama.rw.setText(rs.getString(15));
                DialogUtama.rt.setText(rs.getString(16));
                DialogUtama.comboagama.setSelectedItem(rs.getString(17));
                DialogUtama.no_telp.setText(rs.getString(18));
                DialogUtama.no_wa.setText(rs.getString(19));
                DialogUtama.email.setText(rs.getString(20));
                DialogUtama.combonamabank.setSelectedItem(rs.getString(21));
                DialogUtama.no_rek.setText(rs.getString(22));
                DialogUtama.tps.setText(rs.getString(23));
                DialogUtama.penanggung.setText(rs.getString(24));
                //        txtadmin.setText(rs.getString(24));
                DialogUtama.jenis.setSelectedItem(rs.getString(26));

                JOptionPane.showMessageDialog(null,"Data : "
                    + kolommaster.getText() + " ditemukan");
                DialogUtama dlg = new DialogUtama(this, true);
                dlg.setVisible(true);
                kosong_data();
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak Ada");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data tidak ada!");
            System.out.println(e.getMessage());
        }
        buttonmaster.requestFocus();
    }//GEN-LAST:event_btnmasterActionPerformed

    private void kolommasterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolommasterKeyTyped
        // TODO add your handling code here:
//        filterhuruf(evt);
    }//GEN-LAST:event_kolommasterKeyTyped

    private void kolommasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolommasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolommasterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonmaster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kolommaster;
    // End of variables declaration//GEN-END:variables
}
